# Generated by Django 3.1.14 on 2025-06-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('bookId', models.CharField(default='', max_length=255, verbose_name='bookId')),
                ('tag', models.CharField(default='', max_length=255, verbose_name='tag')),
                ('title', models.CharField(default='', max_length=255, verbose_name='title')),
                ('cover', models.CharField(default='', max_length=2555, verbose_name='cover')),
                ('author', models.CharField(default='', max_length=255, verbose_name='author')),
                ('press', models.CharField(default='', max_length=255, verbose_name='press')),
                ('year', models.CharField(default='', max_length=255, verbose_name='year')),
                ('pageNum', models.CharField(default='', max_length=255, verbose_name='pageNum')),
                ('price', models.CharField(default='', max_length=255, verbose_name='price')),
                ('rate', models.CharField(default='', max_length=255, verbose_name='rate')),
                ('startList', models.CharField(default='', max_length=255, verbose_name='startList')),
                ('summary', models.TextField(default='', verbose_name='summary')),
                ('detailLink', models.CharField(default='', max_length=255, verbose_name='detailLink')),
                ('createTime', models.CharField(default='', max_length=2555, verbose_name='createTime')),
                ('comment_len', models.CharField(default='', max_length=255, verbose_name='comment_len')),
                ('commentList', models.TextField(default='', verbose_name='commentList')),
            ],
            options={
                'db_table': 'booklist',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('username', models.CharField(default='', max_length=255, verbose_name='user')),
                ('password', models.CharField(default='', max_length=255, verbose_name='password')),
                ('createTime', models.DateField(auto_now_add=True, verbose_name='createTime')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
